<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mohammads-MacBook-Pro.local" ignored="3" name="RegressionTest" tests="3" failures="1" timestamp="2022-06-25T17:40:39 EDT" time="42.933" errors="0">
  <testcase name="validateUpsTrackingErrorMsg_1" time="2.084" classname="com.ups.test.UpsTrackingPageTest"/>
  <testcase name="sumTest" time="0.001" classname="com.ups.test.TestClass">
    <failure type="java.lang.AssertionError" message="did not expect [3] but found [3]">
      <![CDATA[java.lang.AssertionError: did not expect [3] but found [3]
at com.ups.test.TestClass.sumTest(TestClass.java:19)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- sumTest -->
  <testcase name="upsLoginTestWrongUserId" time="5.437" classname="com.ups.test.UpsLoginPageTest"/>
  <testcase name="testCase_2" time="0.0" classname="com.ups.test.UpsTrackingPageTest">
    <ignored/>
  </testcase> <!-- testCase_2 -->
  <testcase name="testCase_1" time="0.0" classname="com.ups.test.UpsTrackingPageTest">
    <ignored/>
  </testcase> <!-- testCase_1 -->
  <testcase name="test" time="0.0" classname="com.ups.test.TestClass">
    <ignored/>
  </testcase> <!-- test -->
</testsuite> <!-- RegressionTest -->
